(resource:intake_esm)=
# Accessing CMIP6 data with intake-esm

Download this notebook 

This notebook demonstrates how to access Google Cloud CMIP6 data using intake-esm.

Intake-esm is a data cataloging utility built on top of intake, pandas, and
xarray. Intake-esm aims to facilitate:

- the discovery of earth’s climate and weather datasets.
- the ingestion of these datasets into xarray dataset containers.

It's basic usage is shown below. To begin, let's import `intake`:

In [1]:
import intake
import xarray as xr

## Load the catalog

At import time, intake-esm plugin is available in intake’s registry as
`esm_datastore` and can be accessed with `intake.open_esm_datastore()` function.
Use the `intake_esm.tutorial.get_url()` method to access smaller subsetted catalogs for tutorial purposes.

In [2]:
import intake_esm
#url = intake_esm.tutorial.get_url('google_cmip6')
#print(url)
url ="https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/pangeo-cmip6.json"

In [3]:
cat = intake.open_esm_datastore(url)
cat

The summary above tells us that this catalog contains 514818 data assets.
We can get more information on the individual data assets contained in the
catalog by looking at the underlying dataframe created when we load the catalog:

In [4]:
cat.df

,activity_id,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,zstore,dcpp_init_year,version
0,HighResMIP,CMCC,CMCC-CM2-HR4,highresSST-present,r1i1p1f1,Amon,ps,gn,gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/...,NaN,20170706
1,HighResMIP,CMCC,CMCC-CM2-HR4,highresSST-present,r1i1p1f1,Amon,rsds,gn,gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/...,NaN,20170706
2,HighResMIP,CMCC,CMCC-CM2-HR4,highresSST-present,r1i1p1f1,Amon,rlus,gn,gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/...,NaN,20170706
3,HighResMIP,CMCC,CMCC-CM2-HR4,highresSST-present,r1i1p1f1,Amon,rlds,gn,gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/...,NaN,20170706
4,HighResMIP,CMCC,CMCC-CM2-HR4,highresSST-present,r1i1p1f1,Amon,psl,gn,gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/...,NaN,20170706
...,...,...,...,...,...,...,...,...,...,...,...
514813,CMIP,EC-Earth-Consortium,EC-Earth3-Veg,historical,r1i1p1f1,Amon,tas,gr,gs://cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-E...,NaN,20211207
514814,CMIP,EC-Earth-Consortium,EC-Earth3-Veg,historical,r1i1p1f1,Amon,tauu,gr,gs://cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-E...,NaN,20211207
514815,CMIP,EC-Earth-Consortium,EC-Earth3-Veg,historical,r1i1p1f1,Amon,hur,gr,gs://cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-E...,NaN,20211207
514816,CMIP,EC-Earth-Consortium,EC-Earth3-Veg,historical,r1i1p1f1,Amon,hus,gr,gs://cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-E...,NaN,20211207
514817,CMIP,EC-Earth-Consortium,EC-Earth3-Veg,historical,r1i1p1f1,Amon,tauv,gr,gs://cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-E...,NaN,20211207

The first data asset listed in the catalog contains:

- the surace pressure (variable_id='ps'), as a function of latitude, longitude, time,

- the high resolution version of the CMCC climate model (source_id='CMCC-CM2-HR4'),

- the high resolution model intercomparison expermenet (experiment_id='HighResMIP'),

- developed by the Euro-Mediterranean Centre on Climate Change (instution_id='CMCC'),

- run as part of the Coupled Model Intercomparison Project (activity_id='CMIP')

And is located in Google Cloud Storage at 'gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/highresSST-present/r1i1p1f1/Amon/ps/gn/v20170706/"

## Finding unique entries

To get unique values for given columns in the catalog, intake-esm provides a
{py:meth}`~intake_esm.core.esm_datastore.unique` method:

Let's query the data catalog to see what models(`source_id`), experiments
(`experiment_id`) and temporal frequencies (`table_id`) are available.

In [6]:
unique = cat.unique()
unique

activity_id            [HighResMIP, CMIP, CFMIP, ScenarioMIP, AerChem...
institution_id         [CMCC, EC-Earth-Consortium, MOHC, ECMWF, NOAA-...
source_id              [CMCC-CM2-HR4, EC-Earth3P-HR, HadGEM3-GC31-MM,...
experiment_id          [highresSST-present, piControl, control-1950, ...
member_id              [r1i1p1f1, r1i3p1f1, r1i2p1f1, r1i1p1f2, r2i1p...
table_id               [Amon, 6hrPlev, 3hr, day, EmonZ, E3hr, 6hrPlev...
variable_id            [ps, rsds, rlus, rlds, psl, hurs, huss, hus, h...
grid_label             [gn, gr, gr1, grz, gr2, gr2z, gr1z, gr3, gm, gnz]
zstore                 [gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4...
dcpp_init_year         [1920.0, 1992.0, 2007.0, 2006.0, 2008.0, 1968....
version                [20170706, 20170811, 20170818, 20170831, 20170...
derived_variable_id                                                   []
dtype: object

In [9]:
unique['source_id']

['CMCC-CM2-HR4',
 'EC-Earth3P-HR',
 'HadGEM3-GC31-MM',
 'HadGEM3-GC31-HM',
 'HadGEM3-GC31-LM',
 'EC-Earth3P',
 'ECMWF-IFS-HR',
 'ECMWF-IFS-LR',
 'HadGEM3-GC31-LL',
 'CMCC-CM2-VHR4',
 'GFDL-CM4',
 'GFDL-AM4',
 'IPSL-CM6A-LR',
 'E3SM-1-0',
 'CNRM-CM6-1',
 'GFDL-ESM4',
 'GFDL-ESM2M',
 'GFDL-CM4C192',
 'GFDL-OM4p5B',
 'GISS-E2-1-G',
 'GISS-E2-1-H',
 'CNRM-ESM2-1',
 'BCC-CSM2-MR',
 'BCC-ESM1',
 'MIROC6',
 'AWI-CM-1-1-MR',
 'EC-Earth3-LR',
 'IPSL-CM6A-ATM-HR',
 'CESM2',
 'CESM2-WACCM',
 'CNRM-CM6-1-HR',
 'MRI-ESM2-0',
 'SAM0-UNICON',
 'GISS-E2-1-G-CC',
 'UKESM1-0-LL',
 'EC-Earth3',
 'EC-Earth3-Veg',
 'FGOALS-f3-L',
 'CanESM5',
 'CanESM5-CanOE',
 'INM-CM4-8',
 'INM-CM5-0',
 'NESM3',
 'MPI-ESM-1-2-HAM',
 'CAMS-CSM1-0',
 'MPI-ESM1-2-LR',
 'MPI-ESM1-2-HR',
 'MRI-AGCM3-2-H',
 'MRI-AGCM3-2-S',
 'MCM-UA-1-0',
 'INM-CM5-H',
 'KACE-1-0-G',
 'NorESM2-LM',
 'FGOALS-f3-H',
 'FGOALS-g3',
 'MIROC-ES2L',
 'FIO-ESM-2-0',
 'NorCPM1',
 'NorESM1-F',
 'MPI-ESM1-2-XR',
 'CESM1-1-CAM5-CMIP5',
 'E3SM-1-1',
 'KIOST-ESM',
 'ACCESS-CM2',
 'NorESM2-MM',
 'ACCESS-ESM1-5',
 'IITM-ESM',
 'GISS-E2-2-G',
 'CESM2-FV2',
 'GISS-E2-2-H',
 'CESM2-WACCM-FV2',
 'CIESM',
 'E3SM-1-1-ECA',
 'TaiESM1',
 'AWI-ESM-1-1-LR',
 'EC-Earth3-Veg-LR',
 'CMCC-ESM2',
 'CMCC-CM2-SR5',
 'EC-Earth3-AerChem',
 'IPSL-CM6A-LR-INCA',
 'IPSL-CM5A2-INCA',
 'BCC-CSM2-HR',
 'EC-Earth3P-VHR',
 'CESM1-WACCM-SC',
 'CAS-ESM2-0',
 'EC-Earth3-CC',
 'MIROC-ES2H',
 'ICON-ESM-LR']

In [13]:
unique['activity_id']

['HighResMIP',
 'CMIP',
 'CFMIP',
 'ScenarioMIP',
 'AerChemMIP',
 'RFMIP',
 'FAFMIP',
 'DAMIP',
 'LUMIP',
 'CDRMIP',
 'GMMIP',
 'C4MIP',
 'OMIP',
 'PMIP',
 'LS3MIP',
 'DCPP',
 'PAMIP',
 'ISMIP6']

In [10]:
experiments = unique['experiment_id']

In [11]:
experiments.sort()
experiments

['1pctCO2',
 '1pctCO2-4xext',
 '1pctCO2-bgc',
 '1pctCO2-cdr',
 '1pctCO2-rad',
 '1pctCO2to4x-withism',
 'abrupt-0p5xCO2',
 'abrupt-2xCO2',
 'abrupt-4xCO2',
 'abrupt-solm4p',
 'abrupt-solp4p',
 'amip',
 'amip-4xCO2',
 'amip-future4K',
 'amip-hist',
 'amip-lwoff',
 'amip-m4K',
 'amip-p4K',
 'amip-p4K-lwoff',
 'aqua-4xCO2',
 'aqua-control',
 'aqua-control-lwoff',
 'aqua-p4K',
 'aqua-p4K-lwoff',
 'control-1950',
 'dcppA-assim',
 'dcppA-hindcast',
 'dcppC-amv-ExTrop-neg',
 'dcppC-amv-ExTrop-pos',
 'dcppC-amv-Trop-neg',
 'dcppC-amv-Trop-pos',
 'dcppC-amv-neg',
 'dcppC-amv-pos',
 'dcppC-atl-control',
 'dcppC-atl-pacemaker',
 'dcppC-hindcast-noAgung',
 'dcppC-hindcast-noElChichon',
 'dcppC-hindcast-noPinatubo',
 'dcppC-ipv-NexTrop-neg',
 'dcppC-ipv-NexTrop-pos',
 'dcppC-ipv-neg',
 'dcppC-ipv-pos',
 'dcppC-pac-control',
 'dcppC-pac-pacemaker',
 'deforest-globe',
 'esm-hist',
 'esm-pi-CO2pulse',
 'esm-pi-cdr-pulse',
 'esm-piControl',
 'esm-piControl-spinup',
 'esm-ssp585',
 'esm-ssp585-ssp126Lu',
 'faf-all',
 'faf-heat',
 'faf-heat-NA0pct',
 'faf-heat-NA50pct',
 'faf-passiveheat',
 'faf-stress',
 'faf-water',
 'futSST-pdSIC',
 'highresSST-future',
 'highresSST-present',
 'hist-1950',
 'hist-1950HC',
 'hist-CO2',
 'hist-GHG',
 'hist-GHG-cmip5',
 'hist-aer',
 'hist-aer-cmip5',
 'hist-bgc',
 'hist-nat',
 'hist-nat-cmip5',
 'hist-noLu',
 'hist-piAer',
 'hist-piNTCF',
 'hist-resIPO',
 'hist-sol',
 'hist-stratO3',
 'hist-totalO3',
 'hist-volc',
 'histSST',
 'histSST-1950HC',
 'histSST-piAer',
 'histSST-piCH4',
 'histSST-piNTCF',
 'histSST-piO3',
 'historical',
 'historical-cmip5',
 'historical-ext',
 'land-hist',
 'land-hist-altStartYear',
 'land-noLu',
 'lgm',
 'lig127k',
 'midHolocene',
 'omip1',
 'pa-futAntSIC',
 'pa-futArcSIC',
 'pa-pdSIC',
 'pa-piAntSIC',
 'pa-piArcSIC',
 'past1000',
 'pdSST-futAntSIC',
 'pdSST-futArcSIC',
 'pdSST-futArcSICSIT',
 'pdSST-futBKSeasSIC',
 'pdSST-futOkhotskSIC',
 'pdSST-pdSIC',
 'pdSST-pdSICSIT',
 'pdSST-piAntSIC',
 'pdSST-piArcSIC',
 'piClim-2xDMS',
 'piClim-2xNOx',
 'piClim-2xVOC',
 'piClim-2xdust',
 'piClim-2xfire',
 'piClim-2xss',
 'piClim-4xCO2',
 'piClim-BC',
 'piClim-CH4',
 'piClim-HC',
 'piClim-N2O',
 'piClim-NOx',
 'piClim-NTCF',
 'piClim-O3',
 'piClim-OC',
 'piClim-SO2',
 'piClim-VOC',
 'piClim-aer',
 'piClim-anthro',
 'piClim-control',
 'piClim-ghg',
 'piClim-histaer',
 'piClim-histall',
 'piClim-histghg',
 'piClim-histnat',
 'piClim-lu',
 'piControl',
 'piControl-cmip5',
 'piControl-spinup',
 'piSST-pdSIC',
 'piSST-piSIC',
 'rcp26-cmip5',
 'rcp45-cmip5',
 'rcp85-cmip5',
 'ssp119',
 'ssp126',
 'ssp126-ssp370Lu',
 'ssp245',
 'ssp245-GHG',
 'ssp245-aer',
 'ssp245-cov-fossil',
 'ssp245-cov-modgreen',
 'ssp245-cov-strgreen',
 'ssp245-covid',
 'ssp245-nat',
 'ssp245-stratO3',
 'ssp370',
 'ssp370-lowNTCF',
 'ssp370-ssp126Lu',
 'ssp370SST',
 'ssp370SST-lowCH4',
 'ssp370SST-lowNTCF',
 'ssp370SST-ssp126Lu',
 'ssp370pdSST',
 'ssp434',
 'ssp460',
 'ssp534-over',
 'ssp585',
 'ssp585-bgc']

In [12]:
unique['table_id'][:10]

['Amon',
 '6hrPlev',
 '3hr',
 'day',
 'EmonZ',
 'E3hr',
 '6hrPlevPt',
 'AERmon',
 'LImon',
 'CFmon']

## Search for specific datasets

The {py:meth}`~intake_esm.core.esm_datastore.search` method allows the user to
perform a query on a catalog using keyword arguments. The keyword argument names
must match column names in the catalog. The search method returns a
subset of the catalog with all the entries that match the provided query.

In the example below, we are are going to search for the following:

- variable_d: `o2` which stands for
  `mole_concentration_of_dissolved_molecular_oxygen_in_sea_water`
- experiments: ['historical', 'ssp585']:
  - historical: all forcing of the recent past.
  - ssp585: emission-driven RCP8.5 based on SSP5.
- table_id: `0yr` which stands for annual mean variables on the ocean grid.
- grid_label: `gn` which stands for data reported on a model's native grid.

```{note}
For more details on the CMIP6 vocabulary, please check this
[website](http://clipc-services.ceda.ac.uk/dreq/index.html), and
[Core Controlled Vocabularies (CVs) for use in CMIP6](https://github.com/WCRP-CMIP/CMIP6_CVs)
GitHub repository.
```

In [ ]:
cat_subset = cat.search(
    experiment_id=["historical", "ssp585"],
    table_id="Oyr",
    variable_id="o2",
    grid_label="gn",
)

cat_subset

## Load datasets using `to_dataset_dict()`

Intake-esm implements convenience utilities for loading the query results into
higher level xarray datasets. The logic for merging/concatenating the query
results into higher level xarray datasets is provided in the input JSON file and
is available under `.aggregation_info` property of the catalog:

In [ ]:
cat.esmcat.aggregation_control

To load data assets into xarray datasets, we need to use the
{py:meth}`~intake_esm.core.esm_datastore.to_dataset_dict` method. This method
returns a dictionary of aggregate xarray datasets as the name hints.

In [ ]:
dset_dict = cat_subset.to_dataset_dict(
    xarray_open_kwargs={"consolidated": True, "decode_times": True, "use_cftime": True}
)

In [ ]:
[key for key in dset_dict.keys()][:10]

We can access a particular dataset as follows:

In [ ]:
ds = dset_dict["CMIP.CCCma.CanESM5.historical.Oyr.gn"]
ds

Let’s create a quick plot for a slice of the data:

In [ ]:
ds.o2.isel(time=0, lev=0, member_id=range(1, 24, 4)).plot(col="member_id", col_wrap=3, robust=True)

## Use custom preprocessing functions

When comparing many models it is often necessary to preprocess (e.g. rename
certain variables) them before running some analysis step. The `preprocess`
argument lets the user pass a function, which is executed for each loaded asset
before combining datasets.

In [ ]:
cat_pp = cat.search(
    experiment_id=["historical"],
    table_id="Oyr",
    variable_id="o2",
    grid_label="gn",
    source_id=["IPSL-CM6A-LR", "CanESM5"],
    member_id="r10i1p1f1",
)
cat_pp.df

In [ ]:
dset_dict_raw = cat_pp.to_dataset_dict(xarray_open_kwargs={"consolidated": True})

for k, ds in dset_dict_raw.items():
    print(f"dataset key={k}\n\tdimensions={sorted(list(ds.dims))}\n")

```{note}
Note that both models follow a different naming scheme. We can define a little
helper function and pass it to `.to_dataset_dict()` to fix this. For
demonstration purposes we will focus on the vertical level dimension which is
called `lev` in `CanESM5` and `olevel` in `IPSL-CM6A-LR`.
```

In [ ]:
def helper_func(ds):
    """Rename `olevel` dim to `lev`"""
    ds = ds.copy()
    # a short example
    if "olevel" in ds.dims:
        ds = ds.rename({"olevel": "lev"})
    return ds

In [ ]:
dset_dict_fixed = cat_pp.to_dataset_dict(xarray_open_kwargs={"consolidated": True}, preprocess=helper_func)

for k, ds in dset_dict_fixed.items():
    print(f"dataset key={k}\n\tdimensions={sorted(list(ds.dims))}\n")

This was just an example for one dimension.

```{note}
Check out [xmip package](https://github.com/jbusecke/xMIP)
for a full renaming function for all available CMIP6 models and some other
utilities.
```

## Load datasets into an xarray-datatree using `to_datatree()`

We can also load our data into an [xarray-datatree](https://xarray-datatree.readthedocs.io/en/latest/) object using the following:

In [ ]:
tree = cat_pp.to_datatree(xarray_open_kwargs={"consolidated": True}, preprocess=helper_func)

print(tree)

## Saving a dataset to disk

Once you have a case you will continue to use, you'll want to save it to a local drive for
further work.  To save on dictionary entry to disk, use `to_netcdf`.

In [ ]:
print(f"{k=}")

In [ ]:
write_it = False
if write_it:
    xr.backends.file_manager.FILE_CACHE.clear()
    dset_dict[k].to_netcdf("test.nc",'w')

In [ ]:
import intake_esm  # just to display version information
intake_esm.show_versions()